#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2012 OpenWrt.org

START=100
STOP=30
NAME=dnspod
PROG=/usr/sbin/IaMHei

start() {
    old_pid=$(pgrep -fo "IaMHei start")
    
    [ -z $old_pid ] && exec ${PROG} start &
}

stop() {
    exec ${PROG} stop
}

restart() {
    stop
    start
}
